### ISSUE TITLE
api.ipgeolocation.io has invalid ssl certificate

### ISSUE THREAD

**Issue by omerbrandis** [IPGeolocation/ip-geolocation-api-java-sdk#19]
hi, 

as of a few days ago, I have been unable to use the service.
( receiving with SSL Exception: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed' )

i've tried checking your certificate using openssl s_client -connect api.ipgeolocation.io:443
I get :
CONNECTED(00000003)
depth=4 O = Digital Signature Trust Co., CN = DST Root CA X3
**verify error:num=10:certificate has expired**
notAfter=Sep 30 14:01:15 2021 GMT

I've also tried to send you a message using the contact us page https://ipgeolocation.io/contact.html
the captcha check keep failing, maybe its due to the same problem.

:-)

**Comment by DaudAhmadJF** [comment]
> I've also tried to send you a message using the contact us page https://ipgeolocation.io/contact.html
the captcha check keep failing, maybe its due to the same problem.

Can you share which browser you are using, most probably problem is with your browser. 

For SSL Certificate: 

![image](https://github.com/IPGeolocation/ip-geolocation-api-java-sdk/assets/152851055/4fa6a683-1912-4d25-8d8b-829160f3df6d)

As you can see here, certificate is valid through Jun 26, 2024. Try checking your firewall not blocking you from accessing our service.

**Comment by DaudAhmadJF** [comment]
Feel free to reach out us here for any questions. [support@ipgeolocation.io](mailto:support@ipgeolocation.io)

**Comment by omerbrandis** [comment]
I looks like there some sort of problem with the cert of Digital Signature Trust Co.
weirder still, it is not consistent across servers or server locations.
thanks,
